export default {
  "items": [
    {
      "categoryId": 36340,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/36340/6347885",
      "priceClass": 3,
      "eventId": 153676080,
      "name": "Joe Russo's Almost Dead",
      "url": "https://www.stubhub.com/joe-russo-s-almost-dead-new-york-tickets-9-6-2024/event/153676080/",
      "dayOfWeek": "Fri",
      "formattedTime": "6:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 50864,
      "venueName": "The Rooftop At Pier 17",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 430684,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/430684/6434374",
      "priceClass": 2,
      "eventId": 153258338,
      "name": "The Notebook",
      "url": "https://www.stubhub.com/the-notebook-musical-new-york-tickets-9-6-2024/event/153258338/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3671,
      "venueName": "Gerald Schoenfeld Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 101920,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/grouping/1504051/t04gihjmmgpdtdbdg2mw",
      "priceClass": 3,
      "eventId": 153152363,
      "name": "Hadestown",
      "url": "https://www.stubhub.com/hadestown-new-york-tickets-9-6-2024/event/153152363/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3830,
      "venueName": "Walter Kerr Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 177138,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/177138/6431132",
      "priceClass": 3,
      "eventId": 153075686,
      "name": "MJ The Musical",
      "url": "https://www.stubhub.com/mj-the-musical-new-york-tickets-9-6-2024/event/153075686/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3728,
      "venueName": "Neil Simon Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 42838,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/42838/6395611",
      "priceClass": 3,
      "eventId": 152892130,
      "name": "The Great Gatsby",
      "url": "https://www.stubhub.com/the-great-gatsby-new-york-tickets-9-6-2024/event/152892130/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3626,
      "venueName": "Broadway Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150204986,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150204986/6430468",
      "priceClass": 3,
      "eventId": 153483638,
      "name": "Oh, Mary!",
      "url": "https://www.stubhub.com/oh-mary-new-york-tickets-9-6-2024/event/153483638/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:30 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3707,
      "venueName": "Lyceum Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 4987,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/4987/6433006",
      "priceClass": 3,
      "eventId": 152544925,
      "name": "Cabaret at the Kit Kat Club",
      "url": "https://www.stubhub.com/cabaret-at-the-kit-kat-club-new-york-new-york-tickets-9-6-2024/event/152544925/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:30 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3608,
      "venueName": "August Wilson Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 1534,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/399065/6317984",
      "priceClass": 3,
      "eventId": 153289933,
      "name": "The Lion King",
      "url": "https://www.stubhub.com/lion-king-new-york-tickets-9-6-2024/event/153289933/",
      "dayOfWeek": "Fri",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3720,
      "venueName": "Minskoff Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 127739,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/127739/6390778",
      "priceClass": 3,
      "eventId": 152521050,
      "name": "& Juliet",
      "url": "https://www.stubhub.com/juliet-new-york-tickets-9-6-2024/event/152521050/",
      "dayOfWeek": "Fri",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 15263,
      "venueName": "Stephen Sondheim Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150322889,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150322889/6434398",
      "priceClass": 3,
      "eventId": 153609496,
      "name": "McNeal",
      "url": "https://www.stubhub.com/mcneal-new-york-tickets-9-6-2024/event/153609496/",
      "dayOfWeek": "Fri",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3828,
      "venueName": "Vivian Beaumont Theatre at Lincoln Center for the Performing Arts - Complex",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 12062,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/12062/6395622",
      "priceClass": 3,
      "eventId": 153028355,
      "name": "Usher",
      "url": "https://www.stubhub.com/usher-brooklyn-tickets-9-6-2024/event/153028355/",
      "dayOfWeek": "Fri",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 17278,
      "venueName": "Barclays Center",
      "formattedVenueLocation": "Brooklyn, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 21717,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/21717/6346623",
      "priceClass": 3,
      "eventId": 152601486,
      "name": "Peter Hook & The Light",
      "url": "https://www.stubhub.com/peter-hook-brooklyn-tickets-9-6-2024/event/152601486/",
      "dayOfWeek": "Fri",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 26728,
      "venueName": "Brooklyn Steel",
      "formattedVenueLocation": "Brooklyn, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 5552,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/5552/6433008",
      "priceClass": 3,
      "eventId": 155213289,
      "name": "Macy Gray",
      "url": "https://www.stubhub.com/macy-gray-new-york-tickets-9-6-2024/event/155213289/",
      "dayOfWeek": "Fri",
      "formattedTime": "9:30 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 150024445,
      "venueName": "City Winery New York - Complex",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 35042,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/35042/6318102",
      "priceClass": 3,
      "eventId": 153274039,
      "name": "Hamilton",
      "url": "https://www.stubhub.com/hamilton-new-york-new-york-tickets-9-7-2024/event/153274039/",
      "dayOfWeek": "Sat",
      "formattedTime": "1:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3762,
      "venueName": "Richard Rodgers Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 24256,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/24256/6397952",
      "priceClass": 3,
      "eventId": 151995566,
      "name": "Little Shop of Horrors",
      "url": "https://www.stubhub.com/little-shop-of-horrors-new-york-new-york-tickets-9-7-2024/event/151995566/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 96538,
      "venueName": "Westside Theatre Upstairs",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 102774,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/102774/6430405",
      "priceClass": 3,
      "eventId": 153605314,
      "name": "The Outsiders",
      "url": "https://www.stubhub.com/the-outsiders-new-york-tickets-9-7-2024/event/153605314/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3689,
      "venueName": "Bernard B Jacobs Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150043364,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150043364/6394846",
      "priceClass": 3,
      "eventId": 152302980,
      "name": "Water for Elephants",
      "url": "https://www.stubhub.com/water-for-elephants-new-york-tickets-9-7-2024/event/152302980/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3687,
      "venueName": "Imperial Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 1534,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/399065/6317984",
      "priceClass": 3,
      "eventId": 153289643,
      "name": "The Lion King",
      "url": "https://www.stubhub.com/lion-king-new-york-tickets-9-7-2024/event/153289643/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3720,
      "venueName": "Minskoff Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 3682,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/3682/6381205",
      "priceClass": 3,
      "eventId": 153243067,
      "name": "Wicked the Musical",
      "url": "https://www.stubhub.com/wicked-new-york-tickets-9-7-2024/event/153243067/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3672,
      "venueName": "Gershwin Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 177138,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/177138/6431132",
      "priceClass": 3,
      "eventId": 153075687,
      "name": "MJ The Musical",
      "url": "https://www.stubhub.com/mj-the-musical-new-york-tickets-9-7-2024/event/153075687/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3728,
      "venueName": "Neil Simon Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 4987,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/4987/6433006",
      "priceClass": 3,
      "eventId": 152544926,
      "name": "Cabaret at the Kit Kat Club",
      "url": "https://www.stubhub.com/cabaret-at-the-kit-kat-club-new-york-new-york-tickets-9-7-2024/event/152544926/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3608,
      "venueName": "August Wilson Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 42838,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/42838/6395611",
      "priceClass": 3,
      "eventId": 152892173,
      "name": "The Great Gatsby",
      "url": "https://www.stubhub.com/the-great-gatsby-new-york-tickets-9-7-2024/event/152892173/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3626,
      "venueName": "Broadway Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150204986,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150204986/6430468",
      "priceClass": 3,
      "eventId": 153483564,
      "name": "Oh, Mary!",
      "url": "https://www.stubhub.com/oh-mary-new-york-tickets-9-7-2024/event/153483564/",
      "dayOfWeek": "Sat",
      "formattedTime": "5:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3707,
      "venueName": "Lyceum Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 11874,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/11874/6422870",
      "priceClass": 3,
      "eventId": 153212545,
      "name": "Moulin Rouge",
      "url": "https://www.stubhub.com/moulin-rouge-the-musical-new-york-tickets-9-6-2024/event/153212545/",
      "dayOfWeek": "Fri",
      "formattedTime": "7:00 PM",
      "formattedDateWithoutYear": "Sep 06",
      "startTimestamp": 1725668511507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3593,
      "venueName": "Al Hirschfeld Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 11874,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/11874/6422870",
      "priceClass": 3,
      "eventId": 153212717,
      "name": "Moulin Rouge",
      "url": "https://www.stubhub.com/moulin-rouge-the-musical-new-york-tickets-9-7-2024/event/153212717/",
      "dayOfWeek": "Sat",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3593,
      "venueName": "Al Hirschfeld Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 36340,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/36340/6347885",
      "priceClass": 3,
      "eventId": 153675773,
      "name": "Joe Russo's Almost Dead",
      "url": "https://www.stubhub.com/joe-russo-s-almost-dead-new-york-tickets-9-7-2024/event/153675773/",
      "dayOfWeek": "Sat",
      "formattedTime": "6:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 50864,
      "venueName": "The Rooftop At Pier 17",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 35042,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/35042/6318102",
      "priceClass": 3,
      "eventId": 153273798,
      "name": "Hamilton",
      "url": "https://www.stubhub.com/hamilton-new-york-new-york-tickets-9-7-2024/event/153273798/",
      "dayOfWeek": "Sat",
      "formattedTime": "7:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3762,
      "venueName": "Richard Rodgers Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 24256,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/24256/6397952",
      "priceClass": 3,
      "eventId": 151994073,
      "name": "Little Shop of Horrors",
      "url": "https://www.stubhub.com/little-shop-of-horrors-new-york-new-york-tickets-9-7-2024/event/151994073/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 96538,
      "venueName": "Westside Theatre Upstairs",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 11874,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/11874/6422870",
      "priceClass": 3,
      "eventId": 153212546,
      "name": "Moulin Rouge",
      "url": "https://www.stubhub.com/moulin-rouge-the-musical-new-york-tickets-9-7-2024/event/153212546/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3593,
      "venueName": "Al Hirschfeld Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 102774,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/102774/6430405",
      "priceClass": 3,
      "eventId": 153605228,
      "name": "The Outsiders",
      "url": "https://www.stubhub.com/the-outsiders-new-york-tickets-9-7-2024/event/153605228/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3689,
      "venueName": "Bernard B Jacobs Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 429656,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150004193/6395417",
      "priceClass": 3,
      "eventId": 153713434,
      "name": "Suffs",
      "url": "https://www.stubhub.com/suffs-new-york-tickets-9-7-2024/event/153713434/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3723,
      "venueName": "Music Box Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 1534,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/399065/6317984",
      "priceClass": 3,
      "eventId": 153290213,
      "name": "The Lion King",
      "url": "https://www.stubhub.com/lion-king-new-york-tickets-9-7-2024/event/153290213/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3720,
      "venueName": "Minskoff Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 101920,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/grouping/1504051/t04gihjmmgpdtdbdg2mw",
      "priceClass": 3,
      "eventId": 153152458,
      "name": "Hadestown",
      "url": "https://www.stubhub.com/hadestown-new-york-tickets-9-7-2024/event/153152458/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3830,
      "venueName": "Walter Kerr Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 177138,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/177138/6431132",
      "priceClass": 3,
      "eventId": 153075740,
      "name": "MJ The Musical",
      "url": "https://www.stubhub.com/mj-the-musical-new-york-tickets-9-7-2024/event/153075740/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3728,
      "venueName": "Neil Simon Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 4987,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/4987/6433006",
      "priceClass": 3,
      "eventId": 152545252,
      "name": "Cabaret at the Kit Kat Club",
      "url": "https://www.stubhub.com/cabaret-at-the-kit-kat-club-new-york-new-york-tickets-9-7-2024/event/152545252/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3608,
      "venueName": "August Wilson Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 42838,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/42838/6395611",
      "priceClass": 3,
      "eventId": 152892334,
      "name": "The Great Gatsby",
      "url": "https://www.stubhub.com/the-great-gatsby-new-york-tickets-9-7-2024/event/152892334/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3626,
      "venueName": "Broadway Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 12062,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/12062/6395622",
      "priceClass": 3,
      "eventId": 153028252,
      "name": "Usher",
      "url": "https://www.stubhub.com/usher-brooklyn-tickets-9-7-2024/event/153028252/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:00 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 17278,
      "venueName": "Barclays Center",
      "formattedVenueLocation": "Brooklyn, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150204986,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150204986/6430468",
      "priceClass": 3,
      "eventId": 153483501,
      "name": "Oh, Mary!",
      "url": "https://www.stubhub.com/oh-mary-new-york-tickets-9-7-2024/event/153483501/",
      "dayOfWeek": "Sat",
      "formattedTime": "8:30 PM",
      "formattedDateWithoutYear": "Sep 07",
      startTimestamp: 1725754911507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3707,
      "venueName": "Lyceum Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 5601,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/5601/6431342",
      "priceClass": 3,
      "eventId": 153076086,
      "name": "Minnesota Vikings at New York Giants",
      "url": "https://www.stubhub.com/new-york-giants-east-rutherford-tickets-9-8-2024/event/153076086/",
      "dayOfWeek": "Sun",
      "formattedTime": "1:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 12236,
      "venueName": "MetLife Stadium",
      "formattedVenueLocation": "East Rutherford, NJ, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 35042,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/35042/6318102",
      "priceClass": 3,
      "eventId": 153273896,
      "name": "Hamilton",
      "url": "https://www.stubhub.com/hamilton-new-york-new-york-tickets-9-8-2024/event/153273896/",
      "dayOfWeek": "Sun",
      "formattedTime": "1:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3762,
      "venueName": "Richard Rodgers Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 1534,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/399065/6317984",
      "priceClass": 3,
      "eventId": 153289932,
      "name": "The Lion King",
      "url": "https://www.stubhub.com/lion-king-new-york-tickets-9-8-2024/event/153289932/",
      "dayOfWeek": "Sun",
      "formattedTime": "1:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3720,
      "venueName": "Minskoff Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 11874,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/11874/6422870",
      "priceClass": 3,
      "eventId": 153212716,
      "name": "Moulin Rouge",
      "url": "https://www.stubhub.com/moulin-rouge-the-musical-new-york-tickets-9-8-2024/event/153212716/",
      "dayOfWeek": "Sun",
      "formattedTime": "1:30 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3593,
      "venueName": "Al Hirschfeld Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150204986,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150204986/6430468",
      "priceClass": 3,
      "eventId": 153483562,
      "name": "Oh, Mary!",
      "url": "https://www.stubhub.com/oh-mary-new-york-tickets-9-8-2024/event/153483562/",
      "dayOfWeek": "Sun",
      "formattedTime": "2:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3707,
      "venueName": "Lyceum Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 430684,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/430684/6434374",
      "priceClass": 3,
      "eventId": 153258404,
      "name": "The Notebook",
      "url": "https://www.stubhub.com/the-notebook-musical-new-york-tickets-9-8-2024/event/153258404/",
      "dayOfWeek": "Sun",
      "formattedTime": "3:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3671,
      "venueName": "Gerald Schoenfeld Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 429656,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150004193/6395417",
      "priceClass": 3,
      "eventId": 153713378,
      "name": "Suffs",
      "url": "https://www.stubhub.com/suffs-new-york-tickets-9-8-2024/event/153713378/",
      "dayOfWeek": "Sun",
      "formattedTime": "3:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3723,
      "venueName": "Music Box Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 150322889,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/150322889/6434398",
      "priceClass": 3,
      "eventId": 153610085,
      "name": "McNeal",
      "url": "https://www.stubhub.com/mcneal-new-york-tickets-9-8-2024/event/153610085/",
      "dayOfWeek": "Sun",
      "formattedTime": "3:00 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3828,
      "venueName": "Vivian Beaumont Theatre at Lincoln Center for the Performing Arts - Complex",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 1534,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/399065/6317984",
      "priceClass": 3,
      "eventId": 153289677,
      "name": "The Lion King",
      "url": "https://www.stubhub.com/lion-king-new-york-tickets-9-8-2024/event/153289677/",
      "dayOfWeek": "Sun",
      "formattedTime": "6:30 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 3720,
      "venueName": "Minskoff Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    },
    {
      "categoryId": 127739,
      "imageUrl": "https://media.stubhubstatic.com/stubhub-v2-catalog/d_defaultLogo.jpg/q_auto:low,f_auto,c_fill,g_auto,w_280,h_170,dpr_2.0/categories/127739/6390778",
      "priceClass": 3,
      "eventId": 154378148,
      "name": "& Juliet",
      "url": "https://www.stubhub.com/juliet-new-york-tickets-9-8-2024/event/154378148/",
      "dayOfWeek": "Sun",
      "formattedTime": "6:30 PM",
      "formattedDateWithoutYear": "Sep 08",
      startTimestamp: 1725841311507,
      "isTbd": false,
      "isDateConfirmed": false,
      "isTimeConfirmed": false,
      "eventState": 0,
      "venueId": 15263,
      "venueName": "Stephen Sondheim Theatre",
      "formattedVenueLocation": "New York, NY, USA",
      "timeToEventTotalMilliseconds": 0,
      "hasActiveListings": false,
      "isFavorite": false,
      "aggregateFavorites": 0,
      "isParkingEvent": false,
      "priceTrendPercentage": 0,
      "isRefetchedGlobalEvent": false
    }
  ],
  "sortType": 1,
  "page": 0,
  "remaining": 1,
  "total": 0,
  "venues": []
}
